# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
#####
---
version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.15.0
jobs:
  build:
    docker:
      - image: "python:3.7.3-stretch"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: which OS?
          command: cat /etc/os-release
      - run:
          name: run lint
          command: |
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            hadolint Dockerfile
  
  push:
    machine: true
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: ox-privatecons
          tag: "latest,v0.1.${CIRCLE_BUILD_NUM}"
          dockerfile: Dockerfile
          path: .
workflows:
  version: 2
  lint_and_push:
    jobs:
      - build
      - push:
          requires:
            - build
          