# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: "httpd:2.4-alpine"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install HTML linter
          command: |
          apt-get install tidy
      - run:
          name: run lint
          command: |
            make lint