# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
---
version: 2.1
jobs:
  one:
    docker:
      - image: "ekostadinov/web-linters"
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: run lint
          command: |
            make lint